GET http://localhost:5087/playergames
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IlROLTk5MzQ2Iiwic3ViIjoiVE4tOTkzNDYiLCJqdGkiOiJhMzVmYTUwNiIsInJvbGUiOiJhZG1pbiIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjYxMjE1IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzMTkiLCJodHRwOi8vbG9jYWxob3N0OjUwODciLCJodHRwczovL2xvY2FsaG9zdDo3MjE3Il0sIm5iZiI6MTcxMzMzNTEzMCwiZXhwIjoxNzIxMTk3NTMwLCJpYXQiOjE3MTMzMzUxMzAsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.5ggGHgTbMA762zom5tie8CSNvDUbKsIMK8lbSz6RTI8



###
GET http://localhost:5087/mygames
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IlJQRyIsInN1YiI6IlJQRyIsImp0aSI6ImE4ZDlkMzc2Iiwicm9sZSI6InBsYXllciIsInN1YnNjcmlwdGlvbiI6InNpbHZlciIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjYxMjE1IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzMTkiLCJodHRwOi8vbG9jYWxob3N0OjUwODciLCJodHRwczovL2xvY2FsaG9zdDo3MjE3Il0sIm5iZiI6MTcxMzMzNjUwMSwiZXhwIjoxNzIxMTk4OTAxLCJpYXQiOjE3MTMzMzY1MDEsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.fXAFS7Dbbw22nTiFsMaORuhgE_4_n-yJYm8VHNJy3v0